### ISSUE TITLE
i18next-wc with stencilJs does not render anything

### ISSUE THREAD

**Issue by gper2020** [spurreiter/i18next-wc#2]
Hello, could you please help me with the following . 
I try to use your library with Stenciljs as per instructions here : https://github.com/spurreiter/i18next-wc 
but e.g the `<intl-message>` tag is not being recognized and does not seem to do anything.

my .tsx code : 

```
import { Component, h, Prop, Event, EventEmitter } from '@stencil/core';
import i18next from 'i18next';
import 'i18next-wc';

declare global {
  interface Window {
    i18next: any;
  }
}
window.i18next = i18next;

const resources = {
  en: {
    translation: {
      mykey: 'my text'
    },
  },
};

i18next.init({
  resources,
  lng: 'en',
  keySeparator: false, // we do not use keys in form messages.welcome
  interpolation: {
    escapeValue: false, // react already safes from xss
  },
});

@Component({
  tag: 'my-component',
  shadow: true,
})
export class MyComponent {

  render() {
    return (
                <p>
                  Foo <intl-message key="mykey" value="Title"></intl-message>
                </p>
    );
  }
}
```

In dev-tools, inspecting the paragraph element shows : 

```
<p>Foo <intl-message value="Title"></intl-message></p>
```

So, I do not see any shadow-dom for your intl-message , it is acting as if it is not recognized at all.

Thank you for your time,

George

**Comment by spurreiter** [comment]
Hi @gper2020, 
I have the strong feeling that I misleadingly have chosen the `key` parameter for the translation key. Nonetheless keyed frameworks are using this parameter for their purpose. No translation key no output...
So it looks we have to find a better parameter name for the translation `key`. Any suggestions? `label`?

**Comment by gper2020** [comment]
Hi, thank you for your reply.Hmm I think my problem is different, as I tried to explain. the <intl-message> tag is not being recognized as a webcomponent. When I inspect that element in dev-tools it does nt have a #shadow-root at all.  

I noticed in your readme in the "Using wit jsx" section : 

```
import { intlMessage } from 'i18next-wc';
```

So i tried that as well but I get an error :

```
'intlMessage' is not exported by ../../node_modules/i18next-wc/dist/index.js
```

**Comment by spurreiter** [comment]
@gper2020 Could you please share your sample project? This would allow me to debug the problem.
